# Generated by Django 4.1.3 on 2022-12-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutimage',
            name='image',
            field=models.ImageField(upload_to='images/about_image'),
        ),
        migrations.AlterField(
            model_name='homeimage',
            name='image',
            field=models.ImageField(upload_to='images/home_image'),
        ),
        migrations.AlterField(
            model_name='logoimage',
            name='image',
            field=models.ImageField(upload_to='images/logo_image'),
        ),
    ]
